import Layout from "./components/Layout";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "vision-3d",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/lastestlogo.svg", // Updated path for the favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/logo/newFaviconPath.svg" type="image/svg+xml" />  Updated path here */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
